### ISSUE TITLE
Some of the LMDB code is public domain

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#3]
For example in [`mdb.c`](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L5075):

> Please do not copyright this code. This code is in the public domain.

**Comment by danshearer** [comment]
This is the same potential issue in some jurisdictions as with the public domain statements in the headers of SQLite source code.

**Comment by danshearer** [comment]
This entry in mdb.c is the only case I can find in all of LMDB. This is different to the SQLite case, which does not ask that the code "not be copyrighted". 

I have contacted the author of the affected hash code in mdb.c

**Comment by danshearer** [comment]
Landon Curt Noll is the author of the FNV hash code in LMDB mdb.c , and he very courteously writes:

What if you replaced:

	Please do not copyright this code. This code is in the public domain.

with:

	Title: FNV Hash
	Author: Landon Curt Noll - http://www.isthe.com/chongo/
	Source: http://www.isthe.com/chongo/tech/comp/fnv
	License: CC BY 4.0 - https://creativecommons.org/licenses/by/4.0/
		Share - copy and redistribute the material in any medium or format
		Adapt - remix, transform, and build upon the material for any purpose, even commercially.
		The licensor cannot revoke these freedoms as long as you follow the license terms.
	NOTE: This code was changed to use the 'CC BY 4.0' license by permission of the author.

I have notified the author of LMDB of this license authorisation.

If LMDB doesn't get updated for this we now know we can do it ourselves, but it would be much better to have it changed upstream.

**Comment by danshearer** [comment]
I conveyed this to the openldap mailing list, with the question and response here: https://www.mail-archive.com/openldap-devel@openldap.org/msg06278.html .

Howard Chu said in his response:  "I'd be more inclined to add at the top of the file "contents copyright hyc unless noted otherwise"  to make it clear that my copyright doesn't apply to the FNV code."

Since Howard wrote the code and is maintainer of liblmdb, that is the decision and presumably it will be in the next release of liblmdb. In any case, as per author Landon Curt Noll's comments in this ticket, it is beyond question that regardless of the wording in mdb.c , there is a clear license to the code that is not Public Domain.

**Comment by danshearer** [comment]
I don't think there is anything more LumoSQL can or should do. Closing.
