### ISSUE TITLE
Minimum version of node.js for benchmarking/src to work

### ISSUE THREAD

**Issue by danshearer** [LumoSQL/archive1-LumoSQL-on-github#30]
I think I understood from Keith that the minimum node version number is 12. Version 8.x is what is shipped with Ubuntu 18.04 . 

Need to check:

* precise minimum nodejs version required
* which common distributions do not have this version
* recommended minimum instructions to install nodejs on these operating systems

**Comment by maxwell-k** [comment]
To answer some of those questions:

- for the test suite that checks the JavaScript code to pass, Node JS 12
- (I'll leave this second question for someone else to answer)
- <https://nodejs.org/en/download/package-manager> 

The requirement for Node JS 12 was documented via [benchmarking/README.md](https://github.com/maxwell-k/LumoSQL/tree/feature/benchmarking/benchmarking#prerequisites) in the [first PR](https://github.com/LumoSQL/LumoSQL/pull/20) that introduced any JavaScript code.

This issue is related to https://github.com/LumoSQL/LumoSQL/pull/31.

**Comment by maxwell-k** [comment]
Node JS 12 is the active long-term-support version:
<https://nodejs.org/en/about/releases/>

**Comment by danshearer** [comment]
Closing. This is documented and also fairly obvious. Thanks.
