### ISSUE TITLE
Comparison table showing bench marking results

### ISSUE THREAD

**Issue by maxwell-k** [LumoSQL/archive1-LumoSQL-on-github#9]
1 Is this at all better than unmodified sqlite? a of 2013 and b of 2019?

2 Are the results in line with what Howard said?

3 Are the results interesting?

Is the speed test disk bound? If yes round in tmpfs

**Comment by danshearer** [comment]
> 1 Is this at all better than unmodified sqlite? a of 2013 and b of 2019?

Once the compile fix is applied as per https://github.com/LumoSQL/LumoSQL/issues/6 , the cut-down speedtest suite can be run. So far it appears the results are not better than unmodified sqlite.

> 2 Are the results in line with what Howard said?

No. Not even close. Some runs have produced good numbers, however, when doing a fresh git clone and carefully using the Makefile tool to get the versions correct etc, these good numbers can't be reproduced.

> 3 Are the results interesting?

Yes. Because this is not expected. More investigation is required.

In addition, it appears unmodified sqlite has improved performance by a factor of nearly 2 in the last six years.

> Is the speed test disk bound? If yes round in tmpfs

No it is not. All tests have been tried with tmpfs too.
